"""New Migration

Revision ID: 536463e33eb3
Revises: 960b7eb1b030
Create Date: 2023-05-10 22:33:15.403150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536463e33eb3'
down_revision = '960b7eb1b030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
